Add TravelPlan Package with TravelPlan and Wishlist Class
AY2021S1-CS2103-T14-3/tp pull request #59
Opened 2020-10-02 06:31 UTC by jeannetoh99

2020-10-02 07:53 UTC, jiaweiteo requested changes
Just some javadocs comments to fix for most of the classes

2020-10-02 07:53 UTC, jiaweiteo commented on src/main/java/seedu/address/model/travelplan/ActivityList.java
> +     * Returns true if a person with the same identity as {@code person} exists in the address book.
Should change person to activity

2020-10-02 07:53 UTC, jiaweiteo commented on src/main/java/seedu/address/model/travelplan/ActivityList.java
> +     * Adds a person to the address book.
Same

2020-10-02 07:53 UTC, jiaweiteo commented on src/main/java/seedu/address/model/wishlist/Wishlist.java
> +     * Creates an AddressBook using the Activitys in the {@code toBeCopied}
Wishlist

2020-10-02 07:53 UTC, jiaweiteo commented on src/main/java/seedu/address/model/wishlist/Wishlist.java
> +     * Replaces the contents of the person list with {@code activities}.
activities

2020-10-02 08:51 UTC, timjkong reviewed
looks good :-) just update the javadocs?

2020-10-02 08:51 UTC, timjkong commented on src/main/java/seedu/address/model/wishlist/Wishlist.java
> +     * Replaces the contents of the person list with {@code activities}.
change person to activity

2020-10-02 08:51 UTC, timjkong commented on src/main/java/seedu/address/model/wishlist/Wishlist.java
> +     * The person must not already exist in the address book.
person change to activity, addressbook change to wishlist

2020-10-02 08:51 UTC, timjkong commented on src/main/java/seedu/address/model/wishlist/Wishlist.java
> +     * {@code key} must exist in the address book.
addressbook change to wishlist

2020-10-02 08:51 UTC, timjkong commented on src/main/java/seedu/address/model/AddressBook.java
> +     * The 'unuasual' code block below is a non-static initialization block, sometimes used to avoid duplication
think you accidentally added 'a'?

2020-10-02 17:05 UTC, lyeyixian commented
Don't merge first after commiting changes. 
I need to think about all the ReadOnlyXXX classes, if they are needed

2020-10-03 04:34 UTC, jiaweiteo approved these changes
LGTM

2020-10-03 04:43 UTC, merged